{
  description = "NixOS homelab configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      # Pin home-manager's nixpkgs to ours so it evaluates against one shared
      # nixpkgs instead of pulling in its own copy.
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix.url = "github:Mic92/sops-nix";
    # Same reasoning as above: avoid a second, independent nixpkgs evaluation.
    sops-nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      nixpkgs,
      home-manager,
      sops-nix,
      ...
    }:
    let
      system = "x86_64-linux";
      # Built explicitly because homeConfigurations.zircon (below) needs a pkgs
      # argument directly; nixosSystem builds its own internally from `system`.
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };
    in
    {
      nixosConfigurations.homelab = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          # Read from the host's own filesystem, not tracked in git: it's
          # machine-specific (disks/UUIDs) and generated by nixos-generate-config
          # on each host, so it can't be a portable, shared repo file.
          /etc/nixos/hardware-configuration.nix
          ./configurations/homelab/configuration.nix
          sops-nix.nixosModules.sops
        ];
      };

      nixosConfigurations.thinkpad = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          /etc/nixos/hardware-configuration.nix
          ./configurations/thinkpad/configuration.nix
          # home-manager is only NixOS-integrated here, not for homelab: thinkpad
          # is zircon's interactive desktop, while homelab is a headless server
          # with no zircon desktop session to manage this way.
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.zircon = import ./home/zircon.nix;

          }
          sops-nix.nixosModules.sops
        ];
      };

      nixosConfigurations.desktop = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          /etc/nixos/hardware-configuration.nix
          ./configurations/desktop/configuration.nix
          # Same desktop-class home-manager wiring as thinkpad, for this second machine.
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.zircon = import ./home/zircon.nix;
          }
          sops-nix.nixosModules.sops
        ];
      };

      # Standalone Home Manager configuration. Usable on any machine with Nix
      # (not just NixOS) via:
      #   nix run home-manager/master -- switch --flake .#zircon
      #   home-manager switch --flake .#zircon
      homeConfigurations.zircon = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [ ./home/zircon.nix ];
      };

      formatter.${system} = pkgs.nixfmt-tree;
    };
}
